name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below allow to run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following token permissions are required:
          #  - public_repo (read-only)
          #  - repo (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: harrison-vc
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Bangkok
          
          # Plugin: Isometric Commit Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Plugin: Languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          
          # Plugin: Habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # Layout
          filename: github-metrics.svg
          optimize: yes
          experimental_features: --graph-mnd-legend
